## Topic Modelling

#### Create Topic Modelling (Key topics that review) and Segemention (Create diffrent cluster for similar review)

###  Data Preparation

In [1]:
#imports
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# read data into a DataFrame
data = pd.read_csv("C:/Users/om\Downloads/Text mining & NLP files/Case Study 4 - Unsupervised Model on Text Data (Yelp)/reviews.csv")

#make a copy of columns I need from raw data
df1 = data.iloc[:, [3,4,5,6,8]]

In [3]:
df1 = df1.rename(columns={"stars":"Score","text":"Text"})
df1.head()

Score                                               Text    type  \
0      5  My wife took me here on my birthday for breakf...  review   
1      5  I have no idea why some people give bad review...  review   
2      4  love the gyro plate. Rice is so good and I als...  review   
3      5  Rosie, Dakota, and I LOVE Chaparral Dog Park!!...  review   
4      5  General Manager Scott Petello is a good egg!!!...  review   

                  user_id  useful  
0  rLtl8ZkDX5vH5nAx9C3q5Q       5  
1  0a2KyEL0d3Yb1V6aivbIuQ       0  
2  0hT2KtfLiobPvh6cDC8JQg       1  
3  uZetl9T0NcROGOyFfughhg       2  
4  vYmM4KTsC8ZfQBg-j5MWkw       0

In [5]:
df1['Bad'] = np.where(df1.Score<=3,1,0) #if review is less then 3 bad else good

In [6]:
# convert text to lowercase
df1.loc[:, 'Text'] = df1['Text'].str.lower()

In [7]:
# get the tf-idf table 

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(min_df = 0.05, max_df=0.95,
                             ngram_range=(1, 1), 
                             stop_words='english')
vectorizer.fit(df1['Text'])

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.float64'>, encoding='utf-8',
                input='content', lowercase=True, max_df=0.95, max_features=None,
                min_df=0.05, ngram_range=(1, 1), norm='l2', preprocessor=None,
                smooth_idf=True, stop_words='english', strip_accents=None,
                sublinear_tf=False, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, use_idf=True, vocabulary=None)

In [8]:
# Create a training data
X_train = vectorizer.transform(df1['Text'])

### Topic Modeling

In [35]:
# ?decomposition.LatentDirichletAllocation

In [25]:
# train a LDA Model

from sklearn import decomposition

lda_model = decomposition.LatentDirichletAllocation(n_components=5, learning_method='batch', max_iter=100) 
#we can create 5, 10 ...component
#learning_method='online' and batch. In batch certain batch go, bydefault 120 batch & analaysis but online is continous process
    #when we have large amout of data, online will be faster then batch.
X_topics = lda_model.fit_transform(X_train)
topic_word = lda_model.components_ #collection of terms 
vocab = vectorizer.get_feature_names() #all the terms used 

In [26]:
np.array(vocab)

array(['10', 'actually', 'amazing', 'area', 'ask', 'asked', 'atmosphere',
       'away', 'awesome', 'bad', 'bar', 'beer', 'best', 'better', 'big',
       'bit', 'bread', 'came', 'check', 'cheese', 'chicken', 'clean',
       'come', 'cool', 'day', 'definitely', 'delicious', 'did', 'didn',
       'different', 'dinner', 'don', 'drink', 'drinks', 'eat', 'enjoy',
       'excellent', 'experience', 'far', 'favorite', 'feel', 'flavor',
       'food', 'free', 'fresh', 'friend', 'friendly', 'friends', 'fries',
       'fun', 'going', 'good', 'got', 'great', 'happy', 'having', 'high',
       'home', 'hot', 'hour', 'house', 'huge', 'inside', 'just', 'kind',
       'know', 'large', 'let', 'like', 'little', 'll', 'location', 'long',
       'look', 'looking', 'lot', 'love', 'lunch', 'make', 'maybe', 'meal',
       'meat', 'menu', 'minutes', 'need', 'new', 'nice', 'night', 'oh',
       'ok', 'old', 'order', 'ordered', 'outside', 'overall', 'people',
       'perfect', 'phoenix', 'pizza', 'place', 'place

In [28]:
topic_word #under each component important of each word, similar to PCA

array([[4.48432933e+00, 2.02462403e-01, 9.35266503e+01, 1.91426197e+01,
        6.44519506e+00, 2.01542379e-01, 7.33555446e+01, 2.02990756e-01,
        8.63301906e+01, 1.97947639e+01, 1.61403648e+01, 2.08735560e+01,
        1.18374585e+02, 1.41127719e+01, 3.29712339e+00, 2.04483396e+01,
        3.18996349e+00, 2.02554581e-01, 5.22262016e+00, 1.76186041e+01,
        2.03483955e-01, 2.05447305e-01, 1.21275421e+01, 2.02315307e-01,
        3.04765316e+00, 5.23871616e+01, 1.04756394e+02, 2.03346073e-01,
        2.02407130e-01, 4.91217086e+00, 1.37868588e+01, 4.72842372e+00,
        8.97269740e+00, 1.38898956e+01, 2.11144729e+01, 8.44648549e+00,
        1.16265920e+02, 2.50058164e+01, 5.91044195e+00, 4.20342521e+01,
        2.04131397e-01, 2.02586954e-01, 2.20709030e+02, 2.47047730e+01,
        4.73029911e+01, 2.03150233e-01, 9.99427283e+01, 1.38926527e+01,
        2.00995539e-01, 1.88876271e+01, 9.98559363e+00, 1.44289610e+02,
        4.94080611e+00, 2.75289709e+02, 3.23270110e+01, 2.056251

In [29]:
#Number of rows is equal to number of componets and column is equal to number of voca

In [30]:
# view the topic models
n_top_words = 10 #Give the top 10 word from each componets 
topic_summaries = []
for i, topic_dist in enumerate(topic_word):
    topic_words = np.array(vocab)[np.argsort(topic_dist)][:-(n_top_words+1):-1] 
    topic_summaries.append(' '.join(topic_words))

topic_summaries

#enumerate automatically cal the range of word
#np.array(vocab)[np.argsort(topic_dist)] sorting the data with its importance, [:-(n_top_words+1):-1 
        #give the top 10 (sorting will be asc)--->[:,-10:-1]
#storing data in topic_summaries

['great food service place good love pizza best excellent delicious',
 'bar place good great beer happy food like drinks hour',
 'chicken good food sauce sandwich place salad lunch cheese like',
 'store like place just ve time don great really good',
 'food good ordered just time place order table didn went']

In [31]:
#These are not sentance, these are giving importantant word frequently occured 
#1 componet is more about food and service 
#2 componet is more about bar
#3 particular type of food (pizza)
#3 store , place
#4 food order
#changing the learning method like batch n online will also impcate the result

### Segmentation

In [44]:
#Apply TfidfVectorizer to review text
from sklearn.cluster import KMeans
from sklearn import metrics

In [45]:
# we create a kmeans model
model = KMeans(n_clusters=4, 
               init='k-means++', 
               max_iter=100, n_init=1,random_state=5)

In [46]:
# apply the model on this prepared data
res = model.fit(X_train)
res

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=100,
       n_clusters=4, n_init=1, n_jobs=None, precompute_distances='auto',
       random_state=5, tol=0.0001, verbose=0)

In [47]:
# Getting the vocalbulary as well as cluster centers
# Firstly, set of words from the tf-idf itself
vocab = vectorizer.get_feature_names()
vocab = np.array(vocab)

In [48]:
# Then, the cluster centers from the model fit that we stored on res
cluster_centers = np.array(res.cluster_centers_)
cluster_centers #we have created 4 cluster mean we have 4 centroid --> no. of rows is 4 and col are voca

array([[0.01046715, 0.00648181, 0.02845055, 0.01354035, 0.00562145,
        0.00482228, 0.03618322, 0.00824887, 0.03396122, 0.01182702,
        0.02832954, 0.02093797, 0.03125292, 0.01683045, 0.01271069,
        0.01520979, 0.01164751, 0.00956072, 0.01328364, 0.01370936,
        0.02102925, 0.01850022, 0.01330902, 0.01705536, 0.01697646,
        0.0265975 , 0.02693295, 0.0136607 , 0.01226253, 0.00951562,
        0.01362131, 0.02043122, 0.01393664, 0.02021423, 0.01546127,
        0.01573605, 0.02505279, 0.02326871, 0.00907827, 0.02264056,
        0.0121319 , 0.00836058, 0.08234844, 0.01138194, 0.02222662,
        0.0072551 , 0.04774567, 0.01558904, 0.0114249 , 0.02367418,
        0.0181804 , 0.04472063, 0.01983287, 0.32739301, 0.0293192 ,
        0.0087962 , 0.00924638, 0.0151451 , 0.01025658, 0.02563593,
        0.01298541, 0.01131466, 0.00794857, 0.03061054, 0.00869669,
        0.00975217, 0.00998901, 0.00856246, 0.03482734, 0.02836316,
        0.01688904, 0.02122639, 0.01217935, 0.01

In [49]:
cluster_centers.shape

(4, 156)

In [50]:
#Concept
x=np.array((0.1,10,0.05,1.5))
print(x)
print(x.argsort()) #argsort return the index not the value

[ 0.1  10.    0.05  1.5 ]
[2 0 3 1]


In [52]:
#sorting the important term in term of index
res.cluster_centers_[1].argsort()

array([125,  67, 148,  88,   4,   5,  23,  84,  55, 153,  49,  73,  60,
       142,  96,  43,  40,  98, 110, 138,  79,   7,  35, 112, 122, 118,
        45,  18,  93, 126, 135,  83, 128, 104,  62, 152,  56,  16, 155,
         1,  39,  38, 133,  59, 114, 117,  66,  72,   0,  64,  61,  74,
       145,  90,  32,  47,  29, 139,  24,  48,  57,   2, 149,  94, 121,
        54,  85,  28,  41,  27, 106, 143,   8, 100,  65, 116, 130,  81,
       140,  11,   3, 108, 147,  71, 124, 120, 154,  87,  97, 132,  50,
        21, 127,  14,  70,  78, 111, 129,  75, 150,  95,  37,  33,  15,
        22, 103, 134,  17, 102, 105, 146,  89, 137,  58,  19,   6, 113,
        52,  30,  10,   9,  80, 131, 151, 123, 115,  25,  31,  44,  76,
       141,  12,  26,  34,  69,  46,  36,  13,  77,  91,  82,  92, 144,
       136,  20,  63,  86, 101,  53,  68, 107, 109, 119,  99,  51,  42],
      dtype=int64)

In [57]:
# sorting the cluster centers
sorted_vals = [res.cluster_centers_[i].argsort() for i in range(0,np.shape(res.cluster_centers_)[0])]

print(sorted_vals)
len(res.cluster_centers_)

[array([ 83,  79,   5, 149,   4, 135, 148,  88,   1,  81, 142,  45, 143,
       110, 130, 112,  62, 129, 104,   7, 124, 106,  41,  67,  64,  55,
        89, 115,  38,  94,  93,  56, 131,  29,  17, 145,  65, 138, 132,
        66,  73, 120,  58,   0, 100,  92, 121, 139,  61,  43,  48, 155,
       134,  16,   9,  91, 147, 133,  40,  72,  28, 127,  97, 140,  14,
       125,  60,  80, 150,  18,  22,   3, 114, 116,  75,  30,  27,  19,
       128,  32, 105,  96, 117, 151, 146, 154, 113,  98,  57,  84,  15,
       111,  34,  47,  90,  35, 137,  78,  74, 126,  13,  70,  24,  23,
       153, 102,  50, 101,  21, 122, 109,  52,  33,  31,  11,  95,  20,
        85,  77,  71,  82,  44,  39, 144,  37,  49,  87, 108,  36, 152,
        59, 141,  25,  26,  10,  69,   2,  54, 118,  63,  12, 107,   8,
       136,  68, 103,  86,   6,  51, 123,  46,  76, 119,  42,  99,  53],
      dtype=int64), array([125,  67, 148,  88,   4,   5,  23,  84,  55, 153,  49,  73,  60,
       142,  96,  43,  40,  98, 110, 138, 

4

In [69]:
print(np.shape(res.cluster_centers_))
print(np.shape(res.cluster_centers_)[0])

(4, 156)
4


In [56]:
# get top 10 words from that cluster(4)
words=set()
for i in range(len(res.cluster_centers_)):
    words = set(vocab[sorted_vals[i][-10:]]) #top 10 word for each cluster 
    print(words)

{'good', 'atmosphere', 'place', 'great', 'love', 'nice', 'food', 'service', 'friendly', 'staff'}
{'good', 'really', 'place', 'great', 'like', 'nice', 'food', 'service', 'restaurant', 'pretty'}
{'chicken', 'time', 'place', 'pizza', 'love', 'best', 've', 'delicious', 'store', 'friendly'}
{'good', 'really', 'time', 'don', 'just', 'didn', 'like', 'know', 'little', 'place'}


In [65]:
#1 cluster talking about food ambiance
#2 cluster talking about food amibence food
#3 cluster time plcae food

In [58]:
words=list(words)

In [62]:
#add top words to train set
train_set=X_train[:,[np.argwhere(vocab==i)[0][0] for i in words]]
df1['cluster'] = model.labels_
df1.head()

Score                                               Text    type  \
0      5  my wife took me here on my birthday for breakf...  review   
1      5  i have no idea why some people give bad review...  review   
2      4  love the gyro plate. rice is so good and i als...  review   
3      5  rosie, dakota, and i love chaparral dog park!!...  review   
4      5  general manager scott petello is a good egg!!!...  review   

                  user_id  useful  Bad  cluster  
0  rLtl8ZkDX5vH5nAx9C3q5Q       5    0        2  
1  0a2KyEL0d3Yb1V6aivbIuQ       0    0        3  
2  0hT2KtfLiobPvh6cDC8JQg       1    0        2  
3  uZetl9T0NcROGOyFfughhg       2    0        2  
4  vYmM4KTsC8ZfQBg-j5MWkw       0    0        3

In [63]:
#well disturubuted segement size
df1['cluster'].value_counts() #well distrubued 

2    3368
3    3139
1    2121
0    1372
Name: cluster, dtype: int64

In [64]:
# what does each cluster look like
df1.groupby('cluster').mean()

Score    useful       Bad
cluster                              
0        4.313411  0.976676  0.112974
1        3.598774  1.137199  0.373880
2        4.017221  1.225059  0.230404
3        3.406817  1.979930  0.450143

In [66]:
#cluster 1 and 2 talking about food bt cluster 1 has high score(4.3) and only 11% reviw are bad with cluster 2